spring.datasource.url=jdbc:sqlite:data/makmur.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
server.port=3001
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.web.resources.static-locations=file:../client/dist/
spring.web.resources.add-mappings=true
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.jackson.property-naming-strategy=SNAKE_CASE