spring.datasource.url=jdbc:sqlite:data/makmur.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
server.port=3001
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jackson.property-naming-strategy=SNAKE_CASE